### ISSUE TITLE
QUESTION: Is this project maintained?

### ISSUE THREAD

**Issue by eriknyk** [facebookarchive/fixed-data-table#408]
well seems this project is not getting more officially support, is this project still maintained?
we should still using fixed-data-table on our projects? or maybe we should migrate to another one. this question because scroll doesn't work on MS Edge, and I have some scroll issues on chrome, and the last commit is from Nov 24, 2015.

Best Regards.

**Comment by andrewmclagan** [comment]
agreed. seems a release and forget...

**Comment by bartvde** [comment]
Yes also what about React 15 support?

**Comment by zpao** [comment]
This project is not actively maintained at the moment. Many of the people involved have taken on other responsibilities and haven't had the time to dedicate to this. I have an in-progress pull request (#402) to make it easier for us to maintain moving forward, but we may need some help after that (I'm not actually involved in the project, just work on open source at FB so have some incentive to make this better). There are some others who want to help so I hope we get it to a good point soon.

In the mean time or if you aren't interested in waiting for the revival, I've heard many good things about https://www.npmjs.com/package/react-virtualized.

**Comment by andrewmclagan** [comment]
Thank you for the response. I would be happy to be involved in this repository moving forward, depending on what decisions are made around CLA and what not.

React Virtualised is great. Although browser support is limited to IE11+, the main reason that we are interested in using this repo. 

For those who are interested the next best option IMO is perhaps http://dynamictyped.github.io/Griddle/ having good browser support down to IE9.

**Comment by KamranAsif** [comment]
Hey folks,

My group is using this library very actively, and we plan to maintain it. 
We've already merged in some pull requests (Notably column drag reorder) and have done several bug fixes and have support for react v15.
We also threw up some [new examples](http://schrodinger.github.io/fixed-data-table/example-collapse-rows.html) to help folks!

Check it out here: [https://github.com/schrodinger/fixed-data-table](https://github.com/schrodinger/fixed-data-table)

**Comment by andrewmclagan** [comment]
At facebook

Please place a deprecated notice on this repo for future developers. Will save allot of people wasted time.

**Comment by vinayaknagpal** [comment]
+1

**Comment by burakcan** [comment]
It's interesting that they're not maintaining this module, because facebook is also using it in power editor.

**Comment by larrydahooster** [comment]
Would be nice to get an official statement. I'd really like to use this library in my project.

**Comment by zpao** [comment]
You can consider my comment above an official statement. I work at Facebook and work with the people involved with this project.

**Comment by bartvde** [comment]
@KamranAsif your new examples link gives a 404

**Comment by KamranAsif** [comment]
@bartvde Updated, we recently renamed it to fixed-data-table-2 to avoid namespace conflict on npm
@zpao Can we get https://github.com/facebook/fixed-data-table/pull/411 merged in?

**Comment by MaffooBristol** [comment]
I'm going to give react-virtualized a go because my experience of this module so far has been very poor and I can't imagine it getting much better...

**Comment by seb0zz** [comment]
What about making https://github.com/schrodinger/fixed-data-table-2 the official repo?

**Comment by JMacLulich** [comment]
Thanks @KamranAsif! Exactly what I was looking for someone who had accepted the column drag reorder PR request.

**Comment by gertsonderby** [comment]
Some sort of obvious notice that this project is in the freezer would be capital. I didn't find this issue until I started looking for ways to apply custom styling to this component. Would've been nice to know to write this component off on day 1 rather than day 3.

**Comment by andrewmclagan** [comment]
Just use react virtualised. But yes I agree, its part of being an open source company.

**Comment by gertsonderby** [comment]
@andrewmclagan That presupposes knowledge of react-virtualized - which is not very publicized, and does not show up in a search for 'react data grid' or 'react data table'. I'm not precisely a beginner - 15 years in the business, most of that in JS and open source environments, only relatively new to React ecosystem - but I had no way to know to 'just use'.

But maybe that highlights an inherent problem with the React ecosystem? Or more generally JS?

**Comment by andrewmclagan** [comment]
Yeah agreed. The JS community is very fragmented, although IMO its a result of its size and speed of growth. This repo is a prime example of that situation. React virtualised is a little more comprehensive then just a data grid.

**Comment by tannerlinsley** [comment]
At Nozzle.io, we felt a bit weary banking on this repo for mission-critical parts of our app, so we ended up building our own and migrating away.  https://github.com/tannerlinsley/react-table.  Cheers!

**Comment by thomasdavis** [comment]
We migrated to React Virtualized, it is beautiful, high praise and highly recommend!

**Comment by zpao** [comment]
We did not get this to a good place so I have archived the project. Sorry for the confusion and frustration this has caused.
