### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by irium** [facebookarchive/fixed-data-table#489]
Warning: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by kevflynn** [comment]
this was ready to merge #488 but looks like it has conflicts now

**Comment by mb21** [comment]
see [Add README notice that project is not officially/actively maintained](https://github.com/facebook/fixed-data-table/issues/468)

**Comment by zpao** [comment]
I did a quick fix for this, shipped it, and have now officially deprecated this package. Please see the readme for further information.
