### ISSUE TITLE
Update license to MIT in order to align with React.

### ISSUE THREAD

**Issue by thejohnbackes** [facebookarchive/fixed-data-table#506]
Hi!

We currently use Fixed Data Table 2, which inherits its license from this project.
Could the license for Fixed Data Table be updated so that we can drop all BSD+Patents dependencies?

Thanks.

**Comment by thejohnbackes** [comment]
see https://github.com/schrodinger/fixed-data-table-2/issues/229

**Comment by wcjordan** [comment]
@kyldvs @zpao could either of you weigh in here?

**Comment by zpao** [comment]
I will ask around but given the lack of focus on this project, it's not likely to be a high priority.

**Comment by zpao** [comment]
I'm sorry but we won't be doing this. I just shipped out a final release to make this compatible with React v16 and have archived the project.
