### ISSUE TITLE
Performance benchmark?

### ISSUE THREAD

**Issue by gsklee** [facebookarchive/fixed-data-table#73]
I was confronted by my colleagues about the advantages of using this component against simply using HTML `<table>` for rendering and I found I couldn't come up with anything convincing. Most importantly when I mentioned about the alleged performant speed, I can't find any figures to support it. So it might be good if we can come up with performance benchmarks of some sort.

**Comment by yaycmyk** [comment]
Straight out, you can mention that rendering of `<table>` is blocking, in that the browser will not layout and paint the element until all the inner nodes have been computed. Thus, any `<table>` of >~100 rows will suffer from jank any time the whole object is modified and layout must be recomputed.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by thellimist** [comment]
how is it currently?
